default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: emergensqueeze_development

test:
  <<: *default
  database: emergensqueeze_test

staging:
  <<: *default

production:
  <<: *default
